import type { Metadata } from "next"
import { Montserrat } from "next/font/google"

import "./globals.css"

const montserrat = Montserrat({
	subsets: ["latin"],
	display: "swap",
	variable: "--font-montserrat",
	weight: ["400", "500", "600", "700"],
})

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="fr">
			<body
				className={`${montserrat.variable} antialiased mx-auto w-full max-w-screen-2xl font-montserrat`}
			>
				{children}
			</body>
		</html>
	)
}
